// Map definitions. Units: metres, grid resolution 0.5 m. Floor 0 = ground, 1 = upper, 'both' = stairwell.
// Rooms tile each floor completely. Doors are auto-placed on the shared edge between two rooms.
// Door kinds: door | double | arch | vent | gate.  locked: 'inside' (unlock from the room side) | key id.

const R = (id, name, f, x, z, w, d, type, wall, floor, extra = {}) => ({ id, name, f, x, z, w, d, type, wall, floor, ...extra });

export const MAPS = {
  blackwood: {
    id: 'blackwood',
    name: 'Blackwood Manor',
    desc: 'The family seat. Two sprawling floors, a museum of stolen things, and a nursery nobody opens.',
    difficulty: 'Large · 2 floors · 36 rooms',
    size: [40, 30],
    fog: 0x07080b,
    rooms: [
      // ---------------------------------------------------------------- ground floor
      R('library', 'Library', 0, 0, 0, 7, 10, 'library', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('parlor', 'Parlor', 0, 7, 0, 7, 10, 'parlor', 'wallpaper_red', 'parquet', { windows: true }),
      R('foyer', 'Grand Foyer', 0, 14, 0, 12, 10, 'foyer', 'wallpaper_gold', 'tile_checker', { windows: true }),
      R('dining', 'Dining Room', 0, 26, 0, 8, 10, 'dining', 'wallpaper_red', 'parquet', { windows: true }),
      R('billiard', 'Billiard Room', 0, 34, 0, 6, 10, 'billiard', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('hallW', 'West Hall', 0, 0, 10, 18, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('stairs', 'Grand Staircase', 'both', 18, 10, 4, 8, 'stairs', 'wallpaper_gold', 'wood_floor'),
      R('hallE', 'East Hall', 0, 22, 10, 18, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('study', 'Study', 0, 0, 13, 7, 8, 'study', 'wallpaper_blue', 'wood_floor', { windows: true }),
      R('music', 'Music Room', 0, 7, 13, 7, 8, 'music', 'wallpaper_red', 'parquet'),
      R('storeW', 'Storeroom', 0, 14, 13, 4, 8, 'storage', 'plaster', 'wood_floor_light'),
      R('fuse', 'Generator Room', 0, 0, 21, 6, 9, 'fuse', 'brick', 'concrete', { windows: true }),
      R('laundry', 'Laundry', 0, 6, 21, 6, 9, 'laundry', 'tile_wall', 'concrete', { windows: true }),
      R('chapel', 'Chapel', 0, 12, 21, 6, 9, 'chapel', 'plaster', 'stone_floor', { windows: true }),
      R('closet', 'Servants\' Passage', 0, 18, 18, 4, 6, 'storage', 'plaster', 'wood_floor_light'),
      R('cellar', 'Wine Cellar', 0, 18, 24, 4, 6, 'cellar', 'brick', 'concrete', { windows: true }),
      R('kitchen', 'Kitchen', 0, 22, 13, 10, 8, 'kitchen', 'tile_wall', 'tile_checker'),
      R('pantry', 'Pantry', 0, 32, 13, 8, 8, 'pantry', 'plaster', 'wood_floor_light', { windows: true }),
      R('conserv', 'Conservatory', 0, 22, 21, 10, 9, 'conservatory', 'wallpaper_grey', 'stone_floor', { windows: true }),
      R('servants', 'Servants\' Quarters', 0, 32, 21, 8, 9, 'servants', 'plaster', 'wood_floor_light', { windows: true }),
      // ---------------------------------------------------------------- upper floor
      R('galS', 'South Gallery', 1, 0, 0, 40, 3, 'gallery', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('galW', 'West Gallery', 1, 0, 3, 3, 27, 'gallery', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('galE', 'East Gallery', 1, 37, 3, 3, 27, 'gallery', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('galN', 'North Gallery', 1, 3, 27, 34, 3, 'gallery', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('masterBed', 'Master Bedroom', 1, 3, 3, 9, 9, 'bedroom', 'wallpaper_red', 'wood_floor', { master: true }),
      R('masterBath', 'Master Bath', 1, 3, 12, 9, 5, 'bathroom', 'tile_wall', 'tile_checker', { keyRoom: 'iron' }),
      R('sewing', 'Sewing Room', 1, 3, 17, 9, 5, 'sewing', 'wallpaper_blue', 'wood_floor'),
      R('guest2', 'Blue Bedroom', 1, 3, 22, 9, 5, 'bedroom', 'wallpaper_blue', 'wood_floor'),
      R('nursery', 'Nursery', 1, 12, 3, 6, 7, 'nursery', 'wallpaper_gold', 'wood_floor_light'),
      R('linen', 'Linen Room', 1, 18, 3, 4, 7, 'storage', 'plaster', 'wood_floor_light'),
      R('corrW', 'West Corridor', 1, 12, 10, 6, 8, 'hall', 'wallpaper_red', 'wood_floor'),
      R('corrE', 'East Corridor', 1, 22, 10, 6, 8, 'hall', 'wallpaper_red', 'wood_floor'),
      R('guestBed', 'Green Bedroom', 1, 22, 3, 8, 7, 'bedroom', 'wallpaper_green', 'wood_floor'),
      R('guestBath', 'Guest Bath', 1, 30, 3, 7, 7, 'bathroom', 'tile_wall', 'tile_checker'),
      R('museum', 'The Collection', 1, 28, 10, 9, 17, 'museum', 'wallpaper_gold', 'parquet', { keyRoom: 'silver' }),
      R('landing', 'Upper Landing', 1, 12, 18, 16, 4, 'landing', 'wallpaper_red', 'wood_floor'),
      R('servBed', 'Maid\'s Room', 1, 12, 22, 8, 5, 'bedroom', 'plaster', 'wood_floor_light', { small: true }),
      R('attic', 'Box Room', 1, 20, 22, 8, 5, 'storage', 'plaster', 'wood_floor_light'),
    ],
    doors: [
      ['foyer', 'hallW'], ['foyer', 'hallE'], ['foyer', 'stairs', { kind: 'arch' }], ['foyer', 'parlor', { kind: 'double' }],
      ['foyer', 'dining', { kind: 'double' }], ['parlor', 'library'], ['parlor', 'hallW'], ['library', 'hallW'],
      ['hallW', 'study'], ['hallW', 'music'], ['hallW', 'storeW'], ['study', 'music'], ['study', 'fuse'], ['music', 'laundry'],
      ['laundry', 'fuse'], ['laundry', 'chapel', { kind: 'vent' }], ['chapel', 'storeW'], ['chapel', 'closet'],
      ['closet', 'cellar'], ['closet', 'conserv'], ['hallE', 'kitchen'], ['hallE', 'pantry'], ['dining', 'hallE'],
      ['billiard', 'hallE'], ['dining', 'billiard'], ['kitchen', 'pantry'], ['kitchen', 'conserv', { kind: 'double' }],
      ['pantry', 'servants'], ['conserv', 'servants'],
      ['stairs', 'landing', { kind: 'arch' }], ['landing', 'corrW'], ['landing', 'corrE'], ['corrW', 'nursery'],
      ['corrW', 'masterBed'], ['corrW', 'masterBath', { locked: 'inside' }], ['masterBed', 'galS'], ['masterBed', 'galW'],
      ['nursery', 'galS'], ['linen', 'galS'], ['corrE', 'guestBed'], ['corrE', 'museum', { kind: 'double' }],
      ['guestBed', 'guestBath'], ['guestBed', 'galS'], ['guestBath', 'galE'], ['museum', 'galE'], ['landing', 'museum'],
      ['museum', 'attic'], ['museum', 'galN'], ['landing', 'sewing'], ['landing', 'servBed'], ['landing', 'attic'],
      ['sewing', 'galW'], ['guest2', 'galW'], ['guest2', 'galN'], ['servBed', 'galN'], ['attic', 'galN'],
      ['guest2', 'sewing'], ['sewing', 'masterBath', { kind: 'vent' }],
    ],
    gate: { room: 'foyer', side: 'S', at: 20 },
    spawn: { room: 'foyer' },
  },

  ashgrove: {
    id: 'ashgrove',
    name: 'Ashgrove Estate',
    desc: 'A tight country house. Short sightlines, nowhere to breathe. The ghosts find you faster here.',
    difficulty: 'Medium · 2 floors · 28 rooms',
    size: [32, 20],
    fog: 0x080707,
    rooms: [
      R('lounge', 'Lounge', 0, 0, 0, 10, 8, 'parlor', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('foyer', 'Entrance Hall', 0, 10, 0, 8, 8, 'foyer', 'wallpaper_red', 'stone_floor', { windows: true }),
      R('dining', 'Dining Room', 0, 18, 0, 8, 8, 'dining', 'wallpaper_gold', 'parquet', { windows: true }),
      R('kitchen', 'Kitchen', 0, 26, 0, 6, 8, 'kitchen', 'tile_wall', 'tile_checker', { windows: true }),
      R('hallW', 'Hallway', 0, 0, 8, 12, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('stairs', 'Staircase', 'both', 12, 8, 4, 8, 'stairs', 'wallpaper_red', 'wood_floor'),
      R('hallE', 'Back Hall', 0, 16, 8, 16, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('study', 'Study', 0, 0, 11, 6, 9, 'study', 'wallpaper_blue', 'wood_floor', { windows: true }),
      R('fuse', 'Boiler Room', 0, 6, 11, 6, 9, 'fuse', 'brick', 'concrete'),
      R('cellar', 'Root Cellar', 0, 12, 16, 4, 4, 'cellar', 'brick', 'concrete'),
      R('laundry', 'Laundry', 0, 16, 11, 6, 9, 'laundry', 'tile_wall', 'concrete', { windows: true }),
      R('pantry', 'Pantry', 0, 22, 11, 5, 9, 'pantry', 'plaster', 'wood_floor_light', { windows: true }),
      R('servants', 'Servants\' Room', 0, 27, 11, 5, 9, 'servants', 'plaster', 'wood_floor_light', { windows: true }),
      R('galS', 'Front Gallery', 1, 0, 0, 32, 3, 'gallery', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('bed1', 'Master Bedroom', 1, 0, 3, 10, 5, 'bedroom', 'wallpaper_red', 'wood_floor', { master: true, windows: true }),
      R('nursery', 'Nursery', 1, 10, 3, 6, 5, 'nursery', 'wallpaper_gold', 'wood_floor_light'),
      R('bed2', 'Guest Bedroom', 1, 16, 3, 8, 5, 'bedroom', 'wallpaper_green', 'wood_floor'),
      R('bath', 'Bathroom', 1, 24, 3, 8, 5, 'bathroom', 'tile_wall', 'tile_checker', { keyRoom: 'iron', windows: true }),
      R('corrW', 'Upper Hall', 1, 0, 8, 12, 3, 'hall', 'wallpaper_red', 'wood_floor', { windows: true }),
      R('corrE', 'East Hall', 1, 16, 8, 16, 3, 'hall', 'wallpaper_red', 'wood_floor', { windows: true }),
      R('museum', 'Trophy Room', 1, 0, 11, 12, 9, 'museum', 'wallpaper_gold', 'parquet', { keyRoom: 'silver', windows: true }),
      R('landing', 'Landing', 1, 12, 16, 4, 4, 'landing', 'wallpaper_red', 'wood_floor'),
      R('attic', 'Storeroom', 1, 16, 11, 8, 9, 'storage', 'plaster', 'wood_floor_light', { windows: true }),
      R('bed3', 'Old Bedroom', 1, 24, 11, 8, 9, 'bedroom', 'wallpaper_blue', 'wood_floor', { windows: true }),
    ],
    doors: [
      ['foyer', 'lounge', { kind: 'double' }], ['foyer', 'dining', { kind: 'double' }], ['foyer', 'stairs', { kind: 'arch' }],
      ['foyer', 'hallW'], ['foyer', 'hallE'], ['lounge', 'hallW'], ['dining', 'hallE'], ['kitchen', 'hallE'],
      ['dining', 'kitchen'], ['hallW', 'study'], ['hallW', 'fuse'], ['study', 'fuse'], ['fuse', 'cellar'],
      ['laundry', 'cellar', { kind: 'vent' }], ['hallE', 'laundry'], ['hallE', 'pantry'], ['hallE', 'servants'],
      ['pantry', 'laundry'], ['pantry', 'servants'],
      ['stairs', 'landing', { kind: 'arch' }], ['landing', 'museum'], ['landing', 'attic'], ['corrW', 'museum'],
      ['corrE', 'attic'], ['corrE', 'bed3'], ['corrW', 'bed1'], ['corrW', 'nursery'], ['corrE', 'bed2'],
      ['corrE', 'bath', { locked: 'inside' }], ['bath', 'galS', { kind: 'vent' }], ['galS', 'bed1'], ['galS', 'nursery'],
      ['galS', 'bed2'], ['attic', 'bed3'],
    ],
    gate: { room: 'foyer', side: 'S', at: 14 },
    spawn: { room: 'foyer' },
  },

  hollowmere: {
    id: 'hollowmere',
    name: 'Hollowmere Hall',
    desc: 'A long, narrow manor on the marsh. Endless corridors — they will see you coming, and you them.',
    difficulty: 'Large · 2 floors · 30 rooms · long chases',
    size: [48, 16],
    fog: 0x06090a,
    rooms: [
      R('library', 'Library', 0, 0, 0, 8, 6, 'library', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('parlor', 'Parlor', 0, 8, 0, 8, 6, 'parlor', 'wallpaper_red', 'parquet', { windows: true }),
      R('foyer', 'Great Hall', 0, 16, 0, 8, 6, 'foyer', 'wallpaper_gold', 'tile_checker', { windows: true }),
      R('dining', 'Dining Room', 0, 24, 0, 8, 6, 'dining', 'wallpaper_red', 'parquet', { windows: true }),
      R('kitchen', 'Kitchen', 0, 32, 0, 8, 6, 'kitchen', 'tile_wall', 'tile_checker', { windows: true }),
      R('pantry', 'Pantry', 0, 40, 0, 8, 6, 'pantry', 'plaster', 'wood_floor_light', { windows: true }),
      R('hallW', 'West Corridor', 0, 0, 6, 20, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('stairs', 'Staircase', 'both', 20, 6, 4, 8, 'stairs', 'wallpaper_gold', 'wood_floor'),
      R('hallE', 'East Corridor', 0, 24, 6, 24, 3, 'hall', 'wallpaper_grey', 'wood_floor', { windows: true }),
      R('study', 'Study', 0, 0, 9, 8, 7, 'study', 'wallpaper_blue', 'wood_floor', { windows: true }),
      R('fuse', 'Generator Room', 0, 8, 9, 6, 7, 'fuse', 'brick', 'concrete', { windows: true }),
      R('chapel', 'Chapel', 0, 14, 9, 6, 7, 'chapel', 'plaster', 'stone_floor', { windows: true }),
      R('closet', 'Under-stair Closet', 0, 20, 14, 4, 2, 'storage', 'plaster', 'wood_floor_light'),
      R('billiard', 'Billiard Room', 0, 24, 9, 8, 7, 'billiard', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('laundry', 'Laundry', 0, 32, 9, 6, 7, 'laundry', 'tile_wall', 'concrete', { windows: true }),
      R('servants', 'Servants\' Hall', 0, 38, 9, 10, 7, 'servants', 'plaster', 'wood_floor_light', { windows: true }),
      R('bed1', 'Lord\'s Chamber', 1, 0, 0, 10, 6, 'bedroom', 'wallpaper_red', 'wood_floor', { master: true, windows: true }),
      R('bath1', 'Lord\'s Bath', 1, 10, 0, 6, 6, 'bathroom', 'tile_wall', 'tile_checker', { keyRoom: 'iron', windows: true }),
      R('nursery', 'Nursery', 1, 16, 0, 8, 6, 'nursery', 'wallpaper_gold', 'wood_floor_light', { windows: true }),
      R('bed2', 'Lady\'s Chamber', 1, 24, 0, 8, 6, 'bedroom', 'wallpaper_green', 'wood_floor', { windows: true }),
      R('bath2', 'Washroom', 1, 32, 0, 6, 6, 'bathroom', 'tile_wall', 'tile_checker', { windows: true }),
      R('bed3', 'Guest Chamber', 1, 38, 0, 10, 6, 'bedroom', 'wallpaper_blue', 'wood_floor', { windows: true }),
      R('hallW2', 'Upper West Corridor', 1, 0, 6, 20, 3, 'hall', 'wallpaper_red', 'wood_floor', { windows: true }),
      R('hallE2', 'Upper East Corridor', 1, 24, 6, 24, 3, 'hall', 'wallpaper_red', 'wood_floor', { windows: true }),
      R('museum', 'The Collection', 1, 0, 9, 12, 7, 'museum', 'wallpaper_gold', 'parquet', { keyRoom: 'silver', windows: true }),
      R('sewing', 'Sewing Room', 1, 12, 9, 8, 7, 'sewing', 'wallpaper_blue', 'wood_floor', { windows: true }),
      R('landing', 'Landing', 1, 20, 14, 4, 2, 'landing', 'wallpaper_red', 'wood_floor'),
      R('gallery', 'Portrait Gallery', 1, 24, 9, 16, 7, 'gallery', 'wallpaper_grey', 'parquet', { windows: true, portraits: true }),
      R('attic', 'Box Room', 1, 40, 9, 8, 7, 'storage', 'plaster', 'wood_floor_light', { windows: true }),
    ],
    doors: [
      ['foyer', 'parlor', { kind: 'double' }], ['foyer', 'dining', { kind: 'double' }], ['foyer', 'stairs', { kind: 'arch' }],
      ['foyer', 'hallW'], ['library', 'parlor'], ['library', 'hallW'], ['parlor', 'hallW'], ['dining', 'hallE'],
      ['kitchen', 'hallE'], ['pantry', 'hallE'], ['kitchen', 'dining'], ['kitchen', 'pantry'], ['hallW', 'study'],
      ['hallW', 'fuse'], ['hallW', 'chapel'], ['chapel', 'closet'], ['study', 'fuse'], ['hallE', 'billiard'],
      ['hallE', 'laundry'], ['hallE', 'servants'], ['billiard', 'closet', { kind: 'vent' }], ['laundry', 'servants'],
      ['stairs', 'landing', { kind: 'arch' }], ['landing', 'sewing'], ['landing', 'gallery'], ['hallW2', 'bed1'],
      ['hallW2', 'bath1', { locked: 'inside' }], ['bath1', 'nursery', { kind: 'vent' }], ['hallW2', 'nursery'],
      ['hallE2', 'bed2'], ['hallE2', 'bath2'], ['hallE2', 'bed3'], ['hallW2', 'museum'], ['hallW2', 'sewing'],
      ['hallE2', 'gallery', { kind: 'double' }], ['hallE2', 'attic'], ['museum', 'sewing'], ['gallery', 'attic'],
      ['bath2', 'bed3'],
    ],
    gate: { room: 'foyer', side: 'S', at: 20 },
    spawn: { room: 'foyer' },
  },
};

export const MAP_LIST = ['blackwood', 'ashgrove', 'hollowmere'];

export const GHOST_TYPES = {
  widow: { id: 'widow', name: 'The Widow', model: 'ghost_widow', img: '/textures/painting_0.webp',
    blurb: 'Roams silently and weeps. Screams when she spots you and chases for a long time. A flashlight in her face makes her flinch.' },
  child: { id: 'child', name: 'The Hollow Child', model: 'ghost_child', img: '/textures/painting_1.webp',
    blurb: 'Nearly blind, hears everything. Faster than your sprint but bored quickly. Crawls through vents; stares, giggles, vanishes.' },
  warden: { id: 'warden', name: 'The Warden', model: 'ghost_warden', img: '/textures/painting_2.webp',
    blurb: 'Slow but relentless. Tracks you by scent, smashes doors open, his roar freezes your legs. You hear his chain first.' },
};

export const PROFILES = [
  { id: 0, name: 'Ethan', desc: 'Leather jacket', skin: 0xf0c8a8, top: 'Cloth_Jacket', topColor: 0x4a2e1e, pants: 'Pants_Jeans', pantsColor: 0xffffff, shoes: 'Shoes_Boots', hair: 'Hair_Short', hairColor: 0x2a1a10, hat: null, backpack: true, glasses: false },
  { id: 1, name: 'Mara', desc: 'Grey hoodie', skin: 0xe8b894, top: 'Cloth_Hoodie', topColor: 0x6a6d72, pants: 'Pants_Cargo', pantsColor: 0x3a3a34, shoes: 'Shoes_Sneakers', hair: 'Hair_Long', hairColor: 0x1b120c, hat: null, backpack: false, glasses: false },
  { id: 2, name: 'Cole', desc: 'Flannel & cap', skin: 0xc68a62, top: 'Cloth_Flannel', topColor: 0x8a2222, pants: 'Pants_Cargo', pantsColor: 0x4e4a3a, shoes: 'Shoes_Boots', hair: 'Hair_Short', hairColor: 0x120c08, hat: 'Hat_Cap', hatColor: 0x223355, backpack: true, glasses: false },
  { id: 3, name: 'Iris', desc: 'Olive jacket, beanie', skin: 0xf5d2b8, top: 'Cloth_Jacket', topColor: 0x4a5236, pants: 'Pants_Jeans', pantsColor: 0x9aa6c0, shoes: 'Shoes_Sneakers', hair: 'Hair_Long', hairColor: 0x8a5a2a, hat: 'Hat_Beanie', hatColor: 0x7a2a2a, backpack: false, glasses: false },
  { id: 4, name: 'Dev', desc: 'Black hoodie', skin: 0x8d5a3c, top: 'Cloth_Hoodie', topColor: 0x1a1a1c, pants: 'Pants_Jeans', pantsColor: 0x6a7080, shoes: 'Shoes_Sneakers', hair: 'Hair_Short', hairColor: 0x0a0806, hat: null, backpack: true, glasses: true },
  { id: 5, name: 'Nora', desc: 'Navy jacket, glasses', skin: 0xd9a57f, top: 'Cloth_Jacket', topColor: 0x1e2a44, pants: 'Pants_Cargo', pantsColor: 0x2e2e2a, shoes: 'Shoes_Boots', hair: 'Hair_Long', hairColor: 0x3a2414, hat: null, backpack: true, glasses: true },
];
